apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
     paths:
     - path: /nagp-k8-app(/|$)(.*)
       pathType: ImplementationSpecific
       backend:
        service:
         name: node-app-service
         port:
          number: 80